data:
    dataset: "PMUB"
    train_dataroot: "data/PMUB-train"
    val_dataroot: "data/PMUB-val"
    sample_dataroot: "data/PMUB-test"
    image_size: 256
    channels: 1
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 4

model:
    type: "sr_ve"
    in_channels: 3
    out_ch: 1
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    attn_resolutions: [16]
    dropout: 0.0
    var_type: fixedsmall
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    num_diffusion_timesteps: 1000

training:
    batch_size: 16
    n_epochs: 10000
    n_iters: 5000000
    snapshot_freq: 5000
    validation_freq: 5000000000

sampling:
    batch_size: 8
    ckpt_id: [45000]
    last_only: True

sampling_inter:
    batch_size: 59
    last_only: True

sampling_fid:
    batch_size: 58
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    beta1: 0.9
    amsgrad: false
    eps: 0.00000001
